a = 10
b = 20
result = (a+b)
print("a=",a,"b=",b,"result:=",result)

# formulae for the area of the rectanlge
#rectangle =2(l+b)

l=21
b=23
result = 2*(l+b)
print("l=",l,"b=",b,"result:=",result)

#formulae for the area of circle = 2*3.1472*r
r=6
result = 2*3.1472*6
print("r=",r,"result:=",result)


# formulae for velocity of kinetic energy = .5*m*v*v
m=5
v=30
result = .5*5*(30*30)
print("m=",m,"v=",v,"result:=",result)

# formulae for pythogarus = h*h=(b*b+O*O)
b=20
o=15
result=(20*15)+(20*15)
print("b=",b,"o=",o,"result:",result)






